In [37]:
pip install pandas

Requirement already satisfied: pandas in c:\python310\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.22.4 in c:\python310\lib\site-packages (from pandas) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\python310\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\python310\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [38]:
import pandas as pd

In [53]:
s1 = pd.Series([50,70,90,20,40], index = ['abc','bcd','cde','def','efg'])
print(s1['a':'d'])

abc    5
bcd    7
cde    9
dtype: int64

In [54]:
s1.max

<bound method Series.max of abc    5
bcd    7
cde    9
def    2
efg    4
dtype: int64>

In [6]:
data = {'roll': [1,2,3,4,5,6,7,8,9,10],
       'marks.s1': [60,40,30,20,50,80,40,30,30,10],
       'marks.s2': [20,30,30,30,50,40,50,60,12,10],
       'marks.s3': [10,40,90,30,40,40,50,60,12,10],
       'results': [0,1,0,1,1,0,0,1,0,1]
       }
print (data)

{'roll': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'marks.s1': [60, 40, 30, 20, 50, 80, 40, 30, 30, 10], 'marks.s2': [20, 30, 30, 30, 50, 40, 50, 60, 12, 10], 'marks.s3': [10, 40, 90, 30, 40, 40, 50, 60, 12, 10], 'results': [0, 1, 0, 1, 1, 0, 0, 1, 0, 1]}

In [8]:
studentdata = pd.DataFrame(data)

In [10]:
print(studentdata)

   roll  marks.s1  marks.s2  marks.s3  results
0     1        60        20        10        0
1     2        40        30        40        1
2     3        30        30        90        0
3     4        20        30        30        1
4     5        50        50        40        1
5     6        80        40        40        0
6     7        40        50        50        0
7     8        30        60        60        1
8     9        30        12        12        0
9    10        10        10        10        1

In [13]:
studentdata = pd.DataFrame (data, index = ['st1','st2','st3','st4','st5','st6','st7','st8','st9','st10',])
print (studentdata)

      roll  marks.s1  marks.s2  marks.s3  results
st1      1        60        20        10        0
st2      2        40        30        40        1
st3      3        30        30        90        0
st4      4        20        30        30        1
st5      5        50        50        40        1
st6      6        80        40        40        0
st7      7        40        50        50        0
st8      8        30        60        60        1
st9      9        30        12        12        0
st10    10        10        10        10        1

In [59]:
studentdata.loc['st7']

roll         7
marks.s1    40
marks.s2    50
marks.s3    50
results      0
Name: st7, dtype: int64

In [60]:
data1 = pd.read_excel('data2.xlsx')
print (data1.head())

    Age  gender  chest_pain_type  Resting_BP  Cholestrol  Fasting_sugar  \
0  70.0     1.0                4       130.0       322.0            0.0
1  67.0     0.0                3       115.0       564.0            0.0
2  57.0     1.0                2       124.0       261.0            0.0
3  64.0     1.0                4       128.0       263.0            0.0
4  74.0     0.0                2       120.0       269.0            0.0

   Resting_ECG  Max_heart_rate  Exercise_induced_angina  ST_Depression  \
0          2.0           109.0                      0.0            2.4
1          2.0           160.0                      0.0            1.6
2          0.0           141.0                      0.0            0.3
3          0.0           105.0                      1.0            0.2
4          2.0           121.0                      1.0            0.2

   Slope_peak_excercise  No_of_major_vessels  Thal  Disease
0                   2.0                  3.0   3.0      2.0
1                   2.0                  0.0   7.0      1.0
2                   1.0                  0.0   7.0      2.0
3                   2.0                  1.0   7.0      1.0
4                   1.0                  1.0   3.0      1.0

In [61]:
data1.head(10)

,Age,gender,chest_pain_type,Resting_BP,Cholestrol,Fasting_sugar,Resting_ECG,Max_heart_rate,Exercise_induced_angina,ST_Depression,Slope_peak_excercise,No_of_major_vessels,Thal,Disease
0,70.0,1.0,4,130.0,322.0,0.0,2.0,109.0,0.0,2.4,2.0,3.0,3.0,2.0
1,67.0,0.0,3,115.0,564.0,0.0,2.0,160.0,0.0,1.6,2.0,0.0,7.0,1.0
2,57.0,1.0,2,124.0,261.0,0.0,0.0,141.0,0.0,0.3,1.0,0.0,7.0,2.0
3,64.0,1.0,4,128.0,263.0,0.0,0.0,105.0,1.0,0.2,2.0,1.0,7.0,1.0
4,74.0,0.0,2,120.0,269.0,0.0,2.0,121.0,1.0,0.2,1.0,1.0,3.0,1.0
5,65.0,1.0,4,120.0,177.0,0.0,0.0,140.0,0.0,0.4,1.0,0.0,7.0,1.0
6,56.0,1.0,3,NaN,256.0,1.0,2.0,142.0,1.0,0.6,2.0,1.0,6.0,2.0
7,59.0,1.0,4,110.0,239.0,0.0,2.0,142.0,1.0,1.2,2.0,1.0,7.0,2.0
8,60.0,1.0,4,NaN,293.0,0.0,2.0,170.0,0.0,1.2,2.0,2.0,7.0,2.0
9,63.0,0.0,4,150.0,407.0,0.0,2.0,154.0,0.0,4.0,2.0,3.0,7.0,2.0

In [81]:
data1.tail(10)

,Age,gender,chest_pain_type,Resting_BP,Cholestrol,Fasting_sugar,Resting_ECG,Max_heart_rate,Exercise_induced_angina,ST_Depression,Slope_peak_excercise,No_of_major_vessels,Thal,Disease
260,58.0,0.0,3,120.0,340.0,0.0,0.0,172.0,0.0,0.0,1.0,0.0,3.0,1.0
261,60.0,1.0,4,130.0,206.0,0.0,2.0,132.0,1.0,2.4,2.0,2.0,7.0,2.0
262,58.0,1.0,2,120.0,284.0,0.0,2.0,160.0,0.0,1.8,2.0,0.0,3.0,2.0
263,49.0,1.0,2,130.0,266.0,0.0,0.0,171.0,0.0,0.6,1.0,0.0,3.0,1.0
264,48.0,1.0,2,110.0,229.0,0.0,0.0,168.0,0.0,1.0,3.0,0.0,7.0,2.0
265,52.0,1.0,3,172.0,199.0,1.0,0.0,162.0,0.0,0.5,1.0,0.0,7.0,1.0
266,44.0,1.0,2,120.0,263.0,0.0,0.0,173.0,0.0,0.0,1.0,0.0,7.0,1.0
267,56.0,0.0,2,140.0,294.0,0.0,2.0,153.0,0.0,1.3,2.0,0.0,3.0,1.0
268,57.0,1.0,4,140.0,192.0,0.0,0.0,148.0,0.0,0.4,2.0,0.0,6.0,1.0
269,67.0,1.0,4,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2.0

In [83]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 267 entries, 0 to 269
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      264 non-null    float64
 1   gender                   265 non-null    float64
 2   chest_pain_type          267 non-null    int64
 3   Resting_BP               263 non-null    float64
 4   Cholestrol               264 non-null    float64
 5   Fasting_sugar            263 non-null    float64
 6   Resting_ECG              262 non-null    float64
 7   Max_heart_rate           263 non-null    float64
 8   Exercise_induced_angina  264 non-null    float64
 9   ST_Depression            262 non-null    float64
 10  Slope_peak_excercise     263 non-null    float64
 11  No_of_major_vessels      261 non-null    float64
 12  Thal                     259 non-null    float64
 13  Disease                  261 non-null    float64
dtypes: float64(13), int64(1)
memory usage: 31.3 KB

In [64]:
data1.shape

(270, 14)

In [65]:
data1 = data1.drop_duplicates()

In [66]:
data1.shape

(267, 14)

In [86]:
data1.columns

Index(['Age', 'gender', 'chest_pain_type', 'Resting_BP', 'Cholestrol',
       'Fasting_sugar', 'Resting_ECG', 'Max_heart_rate',
       'Exercise_induced_angina', 'ST_Depression', 'Slope_peak_excercise',
       'No_of_major_vessels', 'Thal', 'Disease'],
      dtype='object')

In [68]:
data1[['Age']]

      Age
0    70.0
1    67.0
2    57.0
3    64.0
4    74.0
..    ...
265  52.0
266  44.0
267  56.0
268  57.0
269  67.0

[267 rows x 1 columns]

In [70]:
data1.rename(columns = {'Age': 'ages','gender': 'Genders'})

,ages,Genders,chest_pain_type,Resting_BP,Cholestrol,Fasting_sugar,Resting_ECG,Max_heart_rate,Exercise_induced_angina,ST_Depression,Slope_peak_excercise,No_of_major_vessels,Thal,Disease
0,70.0,1.0,4,130.0,322.0,0.0,2.0,109.0,0.0,2.4,2.0,3.0,3.0,2.0
1,67.0,0.0,3,115.0,564.0,0.0,2.0,160.0,0.0,1.6,2.0,0.0,7.0,1.0
2,57.0,1.0,2,124.0,261.0,0.0,0.0,141.0,0.0,0.3,1.0,0.0,7.0,2.0
3,64.0,1.0,4,128.0,263.0,0.0,0.0,105.0,1.0,0.2,2.0,1.0,7.0,1.0
4,74.0,0.0,2,120.0,269.0,0.0,2.0,121.0,1.0,0.2,1.0,1.0,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52.0,1.0,3,172.0,199.0,1.0,0.0,162.0,0.0,0.5,1.0,0.0,7.0,1.0
266,44.0,1.0,2,120.0,263.0,0.0,0.0,173.0,0.0,0.0,1.0,0.0,7.0,1.0
267,56.0,0.0,2,140.0,294.0,0.0,2.0,153.0,0.0,1.3,2.0,0.0,3.0,1.0
268,57.0,1.0,4,140.0,192.0,0.0,0.0,148.0,0.0,0.4,2.0,0.0,6.0,1.0
269,67.0,1.0,4,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2.0

In [71]:
data1.dropna()

,Age,gender,chest_pain_type,Resting_BP,Cholestrol,Fasting_sugar,Resting_ECG,Max_heart_rate,Exercise_induced_angina,ST_Depression,Slope_peak_excercise,No_of_major_vessels,Thal,Disease
0,70.0,1.0,4,130.0,322.0,0.0,2.0,109.0,0.0,2.4,2.0,3.0,3.0,2.0
1,67.0,0.0,3,115.0,564.0,0.0,2.0,160.0,0.0,1.6,2.0,0.0,7.0,1.0
2,57.0,1.0,2,124.0,261.0,0.0,0.0,141.0,0.0,0.3,1.0,0.0,7.0,2.0
3,64.0,1.0,4,128.0,263.0,0.0,0.0,105.0,1.0,0.2,2.0,1.0,7.0,1.0
4,74.0,0.0,2,120.0,269.0,0.0,2.0,121.0,1.0,0.2,1.0,1.0,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52.0,1.0,3,172.0,199.0,1.0,0.0,162.0,0.0,0.5,1.0,0.0,7.0,1.0
266,44.0,1.0,2,120.0,263.0,0.0,0.0,173.0,0.0,0.0,1.0,0.0,7.0,1.0
267,56.0,0.0,2,140.0,294.0,0.0,2.0,153.0,0.0,1.3,2.0,0.0,3.0,1.0
268,57.0,1.0,4,140.0,192.0,0.0,0.0,148.0,0.0,0.4,2.0,0.0,6.0,1.0
269,67.0,1.0,4,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2.0

In [72]:
z = data1['Age']

In [73]:
z.head()

0    70.0
1    67.0
2    57.0
3    64.0
4    74.0
Name: Age, dtype: float64

In [74]:
mean = z.mean()

In [75]:
print(mean)

54.53030303030303

In [76]:
z.fillna(mean)

0      70.0
1      67.0
2      57.0
3      64.0
4      74.0
       ...
265    52.0
266    44.0
267    56.0
268    57.0
269    67.0
Name: Age, Length: 267, dtype: float64

In [77]:
data1.shape

(267, 14)

In [97]:
data1.isnull().sum()

Age                        3
gender                     2
chest_pain_type            0
Resting_BP                 4
Cholestrol                 3
Fasting_sugar              4
Resting_ECG                5
Max_heart_rate             4
Exercise_induced_angina    3
ST_Depression              5
Slope_peak_excercise       4
No_of_major_vessels        6
Thal                       8
Disease                    6
dtype: int64

In [1]:
column.max

NameError: name 'column' is not defined

In [79]:
data1.corr()

,Age,gender,chest_pain_type,Resting_BP,Cholestrol,Fasting_sugar,Resting_ECG,Max_heart_rate,Exercise_induced_angina,ST_Depression,Slope_peak_excercise,No_of_major_vessels,Thal,Disease
Age,1.000000,-0.094804,0.099701,0.270403,0.214761,0.125961,0.120065,-0.422259,0.112508,0.185070,0.147619,0.371732,0.107547,0.233503
gender,-0.094804,1.000000,0.035968,-0.065376,-0.193424,0.024607,0.029772,-0.074342,0.177061,0.099209,0.072751,0.074676,0.419427,0.287731
chest_pain_type,0.099701,0.035968,1.000000,-0.047025,0.077527,-0.097896,0.070921,-0.321517,0.342445,0.176513,0.144071,0.239690,0.246423,0.413927
Resting_BP,0.270403,-0.065376,-0.047025,1.000000,0.170747,0.159716,0.096975,-0.036628,0.092549,0.220240,0.135133,0.084527,0.121200,0.174927
Cholestrol,0.214761,-0.193424,0.077527,0.170747,1.000000,0.033715,0.170556,-0.014926,0.084786,0.032237,-0.021765,0.138667,0.023772,0.134944
Fasting_sugar,0.125961,0.024607,-0.097896,0.159716,0.033715,1.000000,0.041090,0.009467,-0.013173,-0.012949,0.057738,0.123842,0.042996,-0.015600
Resting_ECG,0.120065,0.029772,0.070921,0.096975,0.170556,0.041090,1.000000,-0.065733,0.080122,0.099741,0.152306,0.120568,-0.009337,0.175070
Max_heart_rate,-0.422259,-0.074342,-0.321517,-0.036628,-0.014926,0.009467,-0.065733,1.000000,-0.363901,-0.347595,-0.383858,-0.255903,-0.243485,-0.413257
Exercise_induced_angina,0.112508,0.177061,0.342445,0.092549,0.084786,-0.013173,0.080122,-0.363901,1.000000,0.288017,0.265539,0.153233,0.310168,0.416638
ST_Depression,0.185070,0.099209,0.176513,0.220240,0.032237,-0.012949,0.099741,-0.347595,0.288017,1.000000,0.608370,0.258438,0.329829,0.419273
Slope_peak_excercise,0.147619,0.072751,0.144071,0.135133,-0.021765,0.057738,0.152306,-0.383858,0.265539,0.608370,1.000000,0.118614,0.294906,0.343223
No_of_major_vessels,0.371732,0.074676,0.239690,0.084527,0.138667,0.123842,0.120568,-0.255903,0.153233,0.258438,0.118614,1.000000,0.263631,0.447968
Thal,0.107547,0.419427,0.246423,0.121200,0.023772,0.042996,-0.009337,-0.243485,0.310168,0.329829,0.294906,0.263631,1.000000,0.520552
Disease,0.233503,0.287731,0.413927,0.174927,0.134944,-0.015600,0.175070,-0.413257,0.416638,0.419273,0.343223,0.447968,0.520552,1.000000

In [80]:
condition = (data1['Age']>=67)
condition.head()

0     True
1     True
2    False
3    False
4     True
Name: Age, dtype: bool