In [1]:
import numpy as np
import pandas as pd

In [6]:
data = {
    'Name' : ['Kushagra', 'Himanshu', 'Harshit', 'Ojhas', 'Abhishek', 'Adarsh'],
    'City' : ['Prayagraj', 'Kota', 'Gwalior', 'Gwalior', 'Nagpur', 'Jabalpur'],
    'Marks' : [89, 78, 90, 50, 79, 86],
}

In [7]:
df = pd.DataFrame(data)
data

{'Name': ['Kushagra', 'Himanshu', 'Harshit', 'Ojhas', 'Abhishek', 'Adarsh'],
 'City': ['Prayagraj', 'Kota', 'Gwalior', 'Gwalior', 'Nagpur', 'Jabalpur'],
 'Marks': [89, 78, 90, 50, 79, 86]}

In [9]:
df.to_csv('Database.csv')

In [10]:
df.to_csv('Database_NoIndex.csv', index = False)

In [11]:
df.head(2) # shows start 2 indexes

       Name       City  Marks
0  Kushagra  Prayagraj     89
1  Himanshu       Kota     78

In [12]:
df.tail(2) # shows last 2 indexes

       Name      City  Marks
4  Abhishek    Nagpur     79
5    Adarsh  Jabalpur     86

In [13]:
df.describe() # give some information related data from the numerical containing columns from the database.

           Marks
count   6.000000
mean   78.666667
std    14.908610
min    50.000000
25%    78.250000
50%    82.500000
75%    88.250000
max    90.000000

In [15]:
info = pd.read_csv('Info.csv')
info

       Name       City  Marks     Bandi
0  Kushagra  Prayagraj     89        NO
1  Himanshu       Kota     78        NO
2   Harshit    Gwalior     90        NO
3     Ojhas    Gwalior     50       YES
4  Abhishek     Nagpur     79  PROBABLY
5    Adarsh   Jabalpur     86        NO

In [16]:
info['Bandi']

0          NO
1          NO
2          NO
3         YES
4    PROBABLY
5          NO
Name: Bandi, dtype: object

In [30]:
series = pd.Series(np.random.rand(20))
type(series)

pandas.core.series.Series

In [31]:
newdf = pd.DataFrame(np.random.rand(334,5), index = np.arange(334))

In [32]:
newdf.head(5)

          0         1         2         3         4
0  0.586632  0.819719  0.802211  0.028459  0.474266
1  0.423423  0.794289  0.223486  0.892334  0.800107
2  0.974961  0.303110  0.901850  0.240831  0.574523
3  0.240181  0.598833  0.785424  0.219191  0.705363
4  0.983286  0.149499  0.572762  0.789037  0.003976

In [33]:
type(newdf)

pandas.core.frame.DataFrame

In [34]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.490276    0.497107    0.501815    0.496785    0.508166
std      0.292910    0.299030    0.291725    0.301796    0.279854
min      0.003059    0.004408    0.000077    0.002521    0.003822
25%      0.218955    0.233939    0.239443    0.225333    0.263464
50%      0.495190    0.497032    0.506016    0.499124    0.483060
75%      0.752716    0.763853    0.769483    0.769561    0.755337
max      0.997836    0.993720    0.999006    0.998811    0.996675

In [36]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [37]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [38]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [40]:
newdf.to_numpy()

array([[0.58663213, 0.81971881, 0.80221127, 0.0284588 , 0.47426598],
       [0.4234227 , 0.79428878, 0.22348617, 0.89233428, 0.8001075 ],
       [0.97496053, 0.30311017, 0.90184978, 0.24083134, 0.57452253],
       ...,
       [0.30572064, 0.28774462, 0.48881265, 0.47325032, 0.14987209],
       [0.62868749, 0.33304047, 0.86984773, 0.80741463, 0.06034233],
       [0.65727738, 0.22239009, 0.6407864 , 0.73483589, 0.61587769]],
      shape=(334, 5))

In [41]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.586632,0.423423,0.974961,0.240181,0.983286,0.127043,0.105634,0.594566,0.833114,0.283177,...,0.003059,0.017628,0.062781,0.232708,0.450273,0.703674,0.056087,0.305721,0.628687,0.657277
1,0.819719,0.794289,0.303110,0.598833,0.149499,0.676785,0.526775,0.321940,0.673899,0.291019,...,0.197729,0.173369,0.865295,0.546190,0.758996,0.145944,0.804172,0.287745,0.333040,0.222390
2,0.802211,0.223486,0.901850,0.785424,0.572762,0.759500,0.969562,0.989129,0.144721,0.398106,...,0.500576,0.516388,0.369313,0.500581,0.926807,0.131360,0.099061,0.488813,0.869848,0.640786
3,0.028459,0.892334,0.240831,0.219191,0.789037,0.612778,0.223828,0.674128,0.040630,0.687729,...,0.655271,0.499223,0.774344,0.544543,0.230851,0.259964,0.579487,0.473250,0.807415,0.734836
4,0.474266,0.800107,0.574523,0.705363,0.003976,0.326691,0.235866,0.476695,0.643496,0.440643,...,0.798205,0.926242,0.823502,0.444972,0.103820,0.460897,0.685897,0.149872,0.060342,0.615878

In [46]:
newdf.sort_index(axis = 0, ascending = False)

            0         1         2         3         4
333  0.657277  0.222390  0.640786  0.734836  0.615878
332  0.628687  0.333040  0.869848  0.807415  0.060342
331  0.305721  0.287745  0.488813  0.473250  0.149872
330  0.056087  0.804172  0.099061  0.579487  0.685897
329  0.703674  0.145944  0.131360  0.259964  0.460897
..        ...       ...       ...       ...       ...
4    0.983286  0.149499  0.572762  0.789037  0.003976
3    0.240181  0.598833  0.785424  0.219191  0.705363
2    0.974961  0.303110  0.901850  0.240831  0.574523
1    0.423423  0.794289  0.223486  0.892334  0.800107
0    0.586632  0.819719  0.802211  0.028459  0.474266

[334 rows x 5 columns]

In [48]:
newdf.sort_index(axis = 1, ascending = False)

            4         3         2         1         0
0    0.474266  0.028459  0.802211  0.819719  0.586632
1    0.800107  0.892334  0.223486  0.794289  0.423423
2    0.574523  0.240831  0.901850  0.303110  0.974961
3    0.705363  0.219191  0.785424  0.598833  0.240181
4    0.003976  0.789037  0.572762  0.149499  0.983286
..        ...       ...       ...       ...       ...
329  0.460897  0.259964  0.131360  0.145944  0.703674
330  0.685897  0.579487  0.099061  0.804172  0.056087
331  0.149872  0.473250  0.488813  0.287745  0.305721
332  0.060342  0.807415  0.869848  0.333040  0.628687
333  0.615878  0.734836  0.640786  0.222390  0.657277

[334 rows x 5 columns]

In [49]:
newdf.head(0)

Empty DataFrame
Columns: [0, 1, 2, 3, 4]
Index: []

In [51]:
type(newdf[0])

pandas.core.series.Series

In [53]:
newdf.columns = list("ABCDE")
newdf

            A         B         C         D         E
0    0.586632  0.819719  0.802211  0.028459  0.474266
1    0.423423  0.794289  0.223486  0.892334  0.800107
2    0.974961  0.303110  0.901850  0.240831  0.574523
3    0.240181  0.598833  0.785424  0.219191  0.705363
4    0.983286  0.149499  0.572762  0.789037  0.003976
..        ...       ...       ...       ...       ...
329  0.703674  0.145944  0.131360  0.259964  0.460897
330  0.056087  0.804172  0.099061  0.579487  0.685897
331  0.305721  0.287745  0.488813  0.473250  0.149872
332  0.628687  0.333040  0.869848  0.807415  0.060342
333  0.657277  0.222390  0.640786  0.734836  0.615878

[334 rows x 5 columns]

In [56]:
newdf.loc[0,0] = 465

In [58]:
newdf

            A         B         C         D         E      0
0    0.586632  0.819719  0.802211  0.028459  0.474266  465.0
1    0.423423  0.794289  0.223486  0.892334  0.800107    NaN
2    0.974961  0.303110  0.901850  0.240831  0.574523    NaN
3    0.240181  0.598833  0.785424  0.219191  0.705363    NaN
4    0.983286  0.149499  0.572762  0.789037  0.003976    NaN
..        ...       ...       ...       ...       ...    ...
329  0.703674  0.145944  0.131360  0.259964  0.460897    NaN
330  0.056087  0.804172  0.099061  0.579487  0.685897    NaN
331  0.305721  0.287745  0.488813  0.473250  0.149872    NaN
332  0.628687  0.333040  0.869848  0.807415  0.060342    NaN
333  0.657277  0.222390  0.640786  0.734836  0.615878    NaN

[334 rows x 6 columns]

In [59]:
newdf.drop(0, axis = 1)

            A         B         C         D         E
0    0.586632  0.819719  0.802211  0.028459  0.474266
1    0.423423  0.794289  0.223486  0.892334  0.800107
2    0.974961  0.303110  0.901850  0.240831  0.574523
3    0.240181  0.598833  0.785424  0.219191  0.705363
4    0.983286  0.149499  0.572762  0.789037  0.003976
..        ...       ...       ...       ...       ...
329  0.703674  0.145944  0.131360  0.259964  0.460897
330  0.056087  0.804172  0.099061  0.579487  0.685897
331  0.305721  0.287745  0.488813  0.473250  0.149872
332  0.628687  0.333040  0.869848  0.807415  0.060342
333  0.657277  0.222390  0.640786  0.734836  0.615878

[334 rows x 5 columns]

In [60]:
newdf.loc[[1,5],['A','E']]

          A         E
1  0.423423  0.800107
5  0.127043  0.326691

In [61]:
newdf.loc[:,['A','E']] # To represent all the rows

            A         E
0    0.586632  0.474266
1    0.423423  0.800107
2    0.974961  0.574523
3    0.240181  0.705363
4    0.983286  0.003976
..        ...       ...
329  0.703674  0.460897
330  0.056087  0.685897
331  0.305721  0.149872
332  0.628687  0.060342
333  0.657277  0.615878

[334 rows x 2 columns]

In [62]:
newdf.loc[[1,5], :] # To represent all the columns

          A         B         C         D         E   0
1  0.423423  0.794289  0.223486  0.892334  0.800107 NaN
5  0.127043  0.676785  0.759500  0.612778  0.326691 NaN

In [65]:
newdf.loc[(newdf['A']<0.3) & (newdf['C']>0.1)] # Condtioning the queries

            A         B         C         D         E   0
3    0.240181  0.598833  0.785424  0.219191  0.705363 NaN
5    0.127043  0.676785  0.759500  0.612778  0.326691 NaN
6    0.105634  0.526775  0.969562  0.223828  0.235866 NaN
9    0.283177  0.291019  0.398106  0.687729  0.440643 NaN
13   0.097700  0.044202  0.550411  0.528014  0.879720 NaN
..        ...       ...       ...       ...       ...  ..
322  0.183112  0.649582  0.162810  0.820764  0.870728 NaN
324  0.003059  0.197729  0.500576  0.655271  0.798205 NaN
325  0.017628  0.173369  0.516388  0.499223  0.926242 NaN
326  0.062781  0.865295  0.369313  0.774344  0.823502 NaN
327  0.232708  0.546190  0.500581  0.544543  0.444972 NaN

[97 rows x 6 columns]

In [66]:
newdf.iloc[0,4]

np.float64(0.47426597563962625)

In [69]:
newdf.drop([0], axis = 1)

            A         B         C         D         E
0    0.586632  0.819719  0.802211  0.028459  0.474266
1    0.423423  0.794289  0.223486  0.892334  0.800107
2    0.974961  0.303110  0.901850  0.240831  0.574523
3    0.240181  0.598833  0.785424  0.219191  0.705363
4    0.983286  0.149499  0.572762  0.789037  0.003976
..        ...       ...       ...       ...       ...
329  0.703674  0.145944  0.131360  0.259964  0.460897
330  0.056087  0.804172  0.099061  0.579487  0.685897
331  0.305721  0.287745  0.488813  0.473250  0.149872
332  0.628687  0.333040  0.869848  0.807415  0.060342
333  0.657277  0.222390  0.640786  0.734836  0.615878

[334 rows x 5 columns]

In [73]:
newdf['B'] = None
newdf.head(5)

          A     B         C         D         E      0
0  0.586632  None  0.802211  0.028459  0.474266  465.0
1  0.423423  None  0.223486  0.892334  0.800107    NaN
2  0.974961  None  0.901850  0.240831  0.574523    NaN
3  0.240181  None  0.785424  0.219191  0.705363    NaN
4  0.983286  None  0.572762  0.789037  0.003976    NaN

In [75]:
newdf['B'].isnull()
newdf.head(5)

          A     B         C         D         E      0
0  0.586632  None  0.802211  0.028459  0.474266  465.0
1  0.423423  None  0.223486  0.892334  0.800107    NaN
2  0.974961  None  0.901850  0.240831  0.574523    NaN
3  0.240181  None  0.785424  0.219191  0.705363    NaN
4  0.983286  None  0.572762  0.789037  0.003976    NaN